[project]
name = "twilio-chatbot-dial-out"
version = "0.1.0"
description = "Twilio dial-out example for Pipecat"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "dotenv>=0.9.9",
  "pipecat-ai[websocket,google,silero,deepgram,runner]>=1.8.0",
  "pipecatcloud>=1.2.0",
  "twilio",
]

[dependency-groups]
dev = [
    "pyright>=1.1.404,<2",
    "ruff>=0.12.11,<1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I", "UP"]
